### ISSUE TITLE
Taro testing error

### ISSUE THREAD

**Issue by chbian** [aviks/Taro.jl#34]
Hi, I got the following Taro testing error. I am running julia-0.6.0 64bit on Win10. I am not sure if it is a JavaCall problem or a Taro problem. Luckily, Taro still works most of the time...

julia> Pkg.test("Taro")
INFO: Testing Taro
Loaded C:\Program Files\Java\jre1.8.0_144\bin\server\jvm.dll

WARNING: deprecated syntax "typealias Workbook JavaObject{Symbol("org.apache.poi.ss.usermodel.Workbook")}" at C:\Users\chbian\.julia\v0.6\Taro\src\hssf.jl:21.
Use "const Workbook = JavaObject{Symbol("org.apache.poi.ss.usermodel.Workbook")}" instead.

WARNING: deprecated syntax "typealias Sheet JavaObject{Symbol("org.apache.poi.ss.usermodel.Sheet")}" at C:\Users\chbian\.julia\v0.6\Taro\src\hssf.jl:27.
Use "const Sheet = JavaObject{Symbol("org.apache.poi.ss.usermodel.Sheet")}" instead.

WARNING: deprecated syntax "typealias Row JavaObject{Symbol("org.apache.poi.ss.usermodel.Row")}" at C:\Users\chbian\.julia\v0.6\Taro\src\hssf.jl:30.
Use "const Row = JavaObject{Symbol("org.apache.poi.ss.usermodel.Row")}" instead.

WARNING: deprecated syntax "typealias Cell JavaObject{Symbol("org.apache.poi.ss.usermodel.Cell")}" at C:\Users\chbian\.julia\v0.6\Taro\src\hssf.jl:35.
Use "const Cell = JavaObject{Symbol("org.apache.poi.ss.usermodel.Cell")}" instead.

WARNING: deprecated syntax "typealias CellStyle JavaObject{Symbol("org.apache.poi.ss.usermodel.CellStyle")}" at C:\Users\chbian\.julia\v0.6\Taro\src\hssf.jl:38.
Use "const CellStyle = JavaObject{Symbol("org.apache.poi.ss.usermodel.CellStyle")}" instead.

WARNING: deprecated syntax "typealias DataFormat JavaObject{Symbol("org.apache.poi.ss.usermodel.DataFormat")}" at C:\Users\chbian\.julia\v0.6\Taro\src\hssf.jl:39.
Use "const DataFormat = JavaObject{Symbol("org.apache.poi.ss.usermodel.DataFormat")}" instead.
WARNING: Array{T}(::Type{T}, m::Int) is deprecated, use Array{T}(m) instead.
Stacktrace:
 [1] depwarn(::String, ::Symbol) at .\deprecated.jl:70
 [2] Array(::Type{AbstractString}, ::Int64) at .\deprecated.jl:57
 [3] extract(::String) at C:\Users\chbian\.julia\v0.6\Taro\src\Taro.jl:75
 [4] include_from_node1(::String) at .\loading.jl:569
 [5] include(::String) at .\sysimg.jl:14
 [6] process_options(::Base.JLOptions) at .\client.jl:305
 [7] _start() at .\client.jl:371
while loading C:\Users\chbian\.julia\v0.6\Taro\test\runtests.jl, in expression starting on line 7
WARNING: Array{T}(::Type{T}, m::Int) is deprecated, use Array{T}(m) instead.
Stacktrace:
 [1] depwarn(::String, ::Symbol) at .\deprecated.jl:70
 [2] Array(::Type{AbstractString}, ::Int64) at .\deprecated.jl:57
 [3] extract(::String) at C:\Users\chbian\.julia\v0.6\Taro\src\Taro.jl:75
 [4] include_from_node1(::String) at .\loading.jl:569
 [5] include(::String) at .\sysimg.jl:14
 [6] process_options(::Base.JLOptions) at .\client.jl:305
 [7] _start() at .\client.jl:371
while loading C:\Users\chbian\.julia\v0.6\Taro\test\runtests.jl, in expression starting on line 12
Exception in thread "main" java.lang.NullPointerException
        at org.apache.poi.poifs.filesystem.NPOIFSFileSystem.<init>(NPOIFSFileSystem.java:236)
        at org.apache.poi.poifs.filesystem.NPOIFSFileSystem.<init>(NPOIFSFileSystem.java:166)
        at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:278)
        at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:250)
        at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:229)
ERROR: LoadError: Error calling Java: java.lang.NullPointerException
Stacktrace:
 [1] geterror(::Bool) at C:\Users\chbian\.julia\v0.6\JavaCall\src\core.jl:270
 [2] _jcall(::JavaCall.JavaMetaClass{Symbol("org.apache.poi.ss.usermodel.WorkbookFactory")}, ::Ptr{Void}, ::Ptr{Void}, ::Type{T} where T, ::Tuple{DataType}, ::JavaCall.JavaObject{Symbol("java.io.File")}, ::Vararg{JavaCall.JavaObject{Symbol("java.io.File")},N} where N) at C:\Users\chbian\.julia\v0.6\JavaCall\src\core.jl:228
 [3] jcall(::Type{JavaCall.JavaObject{Symbol("org.apache.poi.ss.usermodel.WorkbookFactory")}}, ::String, ::Type{T} where T, ::Tuple{DataType}, ::JavaCall.JavaObject{Symbol("java.io.File")}, ::Vararg{JavaCall.JavaObject{Symbol("java.io.File")},N} where N) at C:\Users\chbian\.julia\v0.6\JavaCall\src\core.jl:136
 [4] JavaCall.JavaObject{Symbol("org.apache.poi.ss.usermodel.Workbook")}(::String) at C:\Users\chbian\.julia\v0.6\Taro\src\hssf.jl:203
 [5] readxl(::String, ::String, ::Int64, ::Int64, ::Int64, ::Int64, ::Taro.ParseOptions{String}) at C:\Users\chbian\.julia\v0.6\Taro\src\hssf.jl:130
 [6] #readxl#2(::Bool, ::Array{String,1}, ::Array{String,1}, ::Array{String,1}, ::Array{Symbol,1}, ::Array{Any,1}, ::Int64, ::Array{Int64,1}, ::Bool, ::Taro.#readxl, ::String, ::String, ::String) at C:\Users\chbian\.julia\v0.6\Taro\src\hssf.jl:115
 [7] readxl(::String, ::String, ::String) at C:\Users\chbian\.julia\v0.6\Taro\src\hssf.jl:99
 [8] include_from_node1(::String) at .\loading.jl:569
 [9] include(::String) at .\sysimg.jl:14
 [10] process_options(::Base.JLOptions) at .\client.jl:305
 [11] _start() at .\client.jl:371
while loading C:\Users\chbian\.julia\v0.6\Taro\test\runtests.jl, in expression starting on line 16
===============================================================================================================[ ERROR: Taro ]===============================================================================================================

failed process: Process(`'C:\Users\chbian\AppData\Local\Julia-0.6.0\bin\julia.exe' -Cx86-64 '-JC:\Users\chbian\AppData\Local\Julia-0.6.0\lib\julia\sys.dll' --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes 'C:\Users\chbian\.julia\v0.6\Taro\test\runtests.jl'`, ProcessExited(1)) [1]

=============================================================================================================================================================================================================================================
ERROR: Taro had test errors

**Comment by StefanPofahl** [comment]
Have you figured out, how to cure the problem?
I have the same issue:
```
ERROR: JavaCall.JavaCallError("Cannot find java library jvm.dll\nSearch Path:\n   C:\\data\\git_repos\\hycenta_stefan_pofahl\n   C:\\bin\\winjulia\\bin\\server\n   C:\\bin\\winjulia\\jre\\bin\\server\n   C:\\bin\\winjulia\\bin\\client\n   C:\\bin\\winjulia\\jre\\lib\\server\n   C:\\bin\\winjulia\\lib\\server")
Stacktrace:
 [1] findjvm()
   @ JavaCall C:\Users\stefanpofahl\.julia\packages\JavaCall\MlduK\src\jvm.jl:108
 [2] _init(opts::Vector{String})
   @ JavaCall C:\Users\stefanpofahl\.julia\packages\JavaCall\MlduK\src\jvm.jl:286
 [3] init()
   @ JavaCall C:\Users\stefanpofahl\.julia\packages\JavaCall\MlduK\src\jvm.jl:277
 [4] init()
   @ Taro C:\Users\stefanpofahl\.julia\packages\Taro\7MUCw\src\Taro.jl:21
 [5] top-level scope
   @ c:\data\git_repos\hycenta_stefan_pofahl\julia_scripts\examples\data_import\XLSX\example_using_Taro_to_read_XLSX.jl:9
```
