### ISSUE TITLE
`readxl` requires write access to the XLSX file. Tests fail on non-dev Taro package

### ISSUE THREAD

**Issue by mkitti** [aviks/Taro.jl#55]
`readxl` requires write access to the XLSX file.

```
Jun 21, 2020 11:16:57 AM org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
WARNING: J2KImageReader not loaded. JPEG2000 files will not be processed.
See https://pdfbox.apache.org/2.0/dependencies.html#jai-image-io
for optional dependencies.

Jun 21, 2020 11:16:57 AM org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
WARNING: Tesseract OCR is installed and will be automatically applied to image files unless
you've excluded the TesseractOCRParser from the default parser.
Tesseract may dramatically slow down content extraction (TIKA-2359).
As of Tika 1.15 (and prior versions), Tesseract is automatically called.
In future versions of Tika, users may need to turn the TesseractOCRParser on via TikaConfig.
Jun 21, 2020 11:16:57 AM org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
WARNING: org.xerial's sqlite-jdbc is not loaded.
Please provide the jar on your classpath to parse sqlite files.
See tika-parsers/pom.xml for the correct version.
Exception in thread "main" java.io.FileNotFoundException: /home/mkitti/.julia/packages/Taro/1eT1a/test/df-test.xlsx (Permission denied)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at org.apache.poi.poifs.nio.FileBackedDataSource.newSrcFile(FileBackedDataSource.java:158)
	at org.apache.poi.poifs.nio.FileBackedDataSource.<init>(FileBackedDataSource.java:60)
	at org.apache.poi.poifs.filesystem.POIFSFileSystem.<init>(POIFSFileSystem.java:217)
	at org.apache.poi.poifs.filesystem.POIFSFileSystem.<init>(POIFSFileSystem.java:170)
	at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:300)
	at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:273)
	at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:254)
ERROR: LoadError: JavaCall.JavaCallError("Error calling Java: java.io.FileNotFoundException: /home/mkitti/.julia/packages/Taro/1eT1a/test/df-test.xlsx (Permission denied)")
Stacktrace:
 [1] geterror(::Bool) at /home/mkitti/.julia/dev/JavaCall/src/core.jl:313
 [2] geterror at /home/mkitti/.julia/dev/JavaCall/src/core.jl:298 [inlined]
 [3] _jcall(::JavaMetaClass{Symbol("org.apache.poi.ss.usermodel.WorkbookFactory")}, ::Ptr{Nothing}, ::Ptr{Nothing}, ::Type{T} where T, ::Tuple{DataType}, ::JavaObject{Symbol("java.io.File")}) at /home/mkitti/.julia/dev/JavaCall/src/core.jl:271
 [4] jcall(::Type{JavaObject{Symbol("org.apache.poi.ss.usermodel.WorkbookFactory")}}, ::String, ::Type{T} where T, ::Tuple{DataType}, ::JavaObject{Symbol("java.io.File")}) at /home/mkitti/.julia/dev/JavaCall/src/core.jl:166
 [5] JavaObject{Symbol("org.apache.poi.ss.usermodel.Workbook")}(::String) at /home/mkitti/.julia/packages/Taro/1eT1a/src/hssf.jl:236
 [6] readxl(::String, ::String, ::Int64, ::Int64, ::Int64, ::Int64, ::Taro.ParseOptions{String}) at /home/mkitti/.julia/packages/Taro/1eT1a/src/hssf.jl:133
 [7] readxl(::String, ::String, ::String; header::Bool, nastrings::Array{String,1}, truestrings::Array{String,1}, falsestrings::Array{String,1}, colnames::Array{Symbol,1}, coltypes::Array{Any,1}, skipstart::Int64, skiprows::Array{Int64,1}, skipblanks::Bool) at /home/mkitti/.julia/packages/Taro/1eT1a/src/hssf.jl:118
 [8] readxl(::String, ::String, ::String) at /home/mkitti/.julia/packages/Taro/1eT1a/src/hssf.jl:102
 [9] top-level scope at /home/mkitti/.julia/packages/Taro/1eT1a/test/runtests.jl:19
 [10] include(::String) at ./client.jl:457
 [11] top-level scope at none:6
in expression starting at /home/mkitti/.julia/packages/Taro/1eT1a/test/runtests.jl:19
ERROR: Package Taro errored during testing
```

**Comment by mkitti** [comment]
Fixed by #56
