### ISSUE TITLE
Exception in thread "process reaper" java.lang.StackOverflowError

### ISSUE THREAD

**Issue by AnnaZav** [aviks/Taro.jl#61]
Hello. I got this exception `Exception in thread "process reaper" java.lang.StackOverflowError` trying to run Taro example. How can I solve this?

P.S. It seems the documentation is out of date. In section Extraction `Pkg.dir()` for now is deprecated.

Full code down below.

```
julia> using Taro
[ Info: Precompiling Taro [61d0e4fa-4e73-5030-88a9-ae4c27b203dd]

julia> Taro.init()

julia> testfile = "/home/oem/.julia/packages/Taro/lMmIa/examples/tables.pdf"
"/home/oem/.julia/packages/Taro/lMmIa/examples/tables.pdf"

julia> meta, text = Taro.extract(testfile);
Oct 29, 2020 10:39:08 PM org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
WARNING: J2KImageReader not loaded. JPEG2000 files will not be processed.
See https://pdfbox.apache.org/2.0/dependencies.html#jai-image-io
for optional dependencies.

Oct 29, 2020 10:39:08 PM org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
WARNING: org.xerial's sqlite-jdbc is not loaded.
Please provide the jar on your classpath to parse sqlite files.
See tika-parsers/pom.xml for the correct version.
Exception in thread "process reaper" java.lang.StackOverflowError
        at java.base/java.lang.invoke.MethodType.equals(MethodType.java:830)
        at java.base/java.lang.invoke.MethodType.equals(MethodType.java:822)
        at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:940)
        at java.base/java.lang.invoke.MethodType$ConcurrentWeakInternSet.get(MethodType.java:1317)
        at java.base/java.lang.invoke.MethodType.makeImpl(MethodType.java:312)
        at java.base/java.lang.invoke.MethodTypeForm.canonicalize(MethodTypeForm.java:253)
        at java.base/java.lang.invoke.MethodTypeForm.findForm(MethodTypeForm.java:215)
        at java.base/java.lang.invoke.MethodType.makeImpl(MethodType.java:327)
        at java.base/java.lang.invoke.MethodHandleNatives.findMethodHandleType(MethodHandleNatives.java:377)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:932)
        at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2137)
        at java.base/java.lang.ProcessHandleImpl$1.run(ProcessHandleImpl.java:162)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
```
My configuration
```
julia> versioninfo()
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_COPY_STACKS = 1
```

**Comment by mkitti** [comment]
The error appears to be coming from the Java side.

What Java version are you using? What is the output of
```julia
using JavaCall;
JavaCall.init();
@info "Java Version: ", jcall(@jimport(java.lang.System), "getProperty", JString, (JString,), "java.version")
```

**Comment by AnnaZav** [comment]
Here it is.

```
julia> using JavaCall

julia> JavaCall.init()

julia> @info "Java Version: ", jcall(@jimport(java.lang.System), "getProperty", JString, (JString,), "java.version")
[ Info: ("Java Version: ", "14.0.2")
```

**Comment by mkitti** [comment]
Have you tried any other versions?  There might be a JDK bug.
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8217475

**Comment by AnnaZav** [comment]
You are right! Thank you!
`Java Version: 15.0.1` gives the same endless exception as `14.0.2`, but
`1.8.0_202` works correct!

**Comment by mkitti** [comment]
Thanks. If you have time, could you check Java 11?

**Comment by AnnaZav** [comment]
`[ Info: ("Java Version: ", "11.0.5")` gives same endless bad output.

```
Exception: java.lang.StackOverflowError thrown from the UncaughtExceptionHandler in thread "process reaper"
Exception in thread "process reaper" java.lang.StackOverflowError

Exception: java.lang.StackOverflowError thrown from the UncaughtExceptionHandler in thread "process reaper"
Exception in thread "process reaper" java.lang.StackOverflowError

Exception: java.lang.StackOverflowError thrown from the UncaughtExceptionHandler in thread "process reaper"
Exception in thread "process reaper" java.lang.StackOverflowError
Exception in thread "process reaper" 
Exception: java.lang.StackOverflowError thrown from the UncaughtExceptionHandler in thread "process reaper"
java.lang.StackOverflowError
```
